trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    workingDirectory: './stem-ai'
    displayName: 'npm install'

  - script: |
      npm test
    workingDirectory: './stem-ai'
    displayName: 'npm test'
